### ISSUE TITLE
Add support for testdox

### ISSUE THREAD

**Issue by theofidry** [zf2timo/PHPUnitPrettyResultPrinter#44]
Would be awesome ;)

**Comment by zf2timo** [comment]
If i understand correctly, you like to see the test Methods Name as sentence?

Like this:

```
BankAccount
 [x] Balance is initially zero                 ✔✔✔✔✔✔✔✔✔✔✔   
 [x] Balance cannot become negative            ✔✔✔✔✘✔
```

**Comment by theofidry** [comment]
Well that's what the `--testdox` option does already, what I would wish to have is a colorful out for it as well instead of everything white.

**Comment by zf2timo** [comment]
Ok, i will have a look, how this can be done.

**Comment by zf2timo** [comment]
I run this project with the `--testdox` Parameter and the result is printed in a colorful result.
See the Screenshot:
![image](https://cloud.githubusercontent.com/assets/3073381/16162550/7805b68a-34d4-11e6-9888-79c465171c2f.png)

I think there maybe another error with your terminal.

**Comment by theofidry** [comment]
Did you try with several test methods? I don't see any of them in your output which is very suspicious when using `--testdox`.

**Comment by theofidry** [comment]
The vanilla one looks like that:

<img width="396" alt="screen shot 2016-06-17 at 20 49 34" src="https://cloud.githubusercontent.com/assets/5175937/16162712/0a8ad074-34cd-11e6-9713-b3e227737aec.png">

**Comment by zf2timo** [comment]
I just tried it with the Zend-Diactoros Project. 

And you are right, if i run it with the Nelmia\Alice Project, the output is white.

**Comment by theofidry** [comment]
There is also the edge case of when you have a data provider (in which case your method is tested against different output), is skipped or incomplete. I don't remember what the output is for the first one, but for the other two I think you just get an empty box `[ ]` instead of `[x]`.

**Comment by zf2timo** [comment]
I will close this issue, because it is out of the scope of this module.
The error should be fixed in the testdox Result Printer. (https://github.com/sebastianbergmann/phpunit/blob/094b0fe214928d45ada99e752d8ca06860e4dc70/src/Util/TestDox/ResultPrinter/Text.php#L37)

So please open an issue at the PHPUnit Repository.
